[package]
name = "teste-3"
version = "0.1.0"
edition = "2021"
auhors = ["IanLLHonorio"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.5"
